project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: overall_findings.qmd
        text: Findings
      - text: Cleaning
        menu: 
          - href: cleaning/cleaning_1.qmd
            text: Cleaning This Data
          - href: cleaning/cleaning_2.qmd
            text: Cleaning That Data
      - text: Analysis
        menu: 
          - href: analysis/analysis_placeholder.qmd
            text: Placeholder Analysis
          - href: analysis/another_analysis.qmd
            text: Another Analysis
      - text: Interpretation
        menu: 
          - href: interpretation/interpretation_1.qmd
            text: Interpretation 1



      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

