project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Report
      - text: Cleaning
        menu: 
          - href: cleaning/cleaning_1.qmd
            text: Cleaning This Data
          - href: cleaning/cleaning_2.qmd
            text: Cleaning That Data
      - text: Analysis
        menu: 
          - href: analysis/analysis_placeholder.qmd
            text: Placeholder Analysis
          - href: analysis/another_analysis.qmd
            text: Another Analysis
      - text: Interpretation
        menu: 
          - href: interpretation/interpretation_1.qmd
            text: Interpretation 1
      - href: the_data.qmd
        text: Overview of Data Sources
      - href: bibliography/bibliography.qmd
        text: Bibliography



      


format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 2


editor: visual

