project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: findings.qmd
        text: Findings
      - href: overall_health.qmd
        text: Overall Health
      - href: maternal_health.qmd
        text: Maternal Health
      - href: maternal_wellness.qmd
        text: Maternal Wellness
      - href: child_health.qmd
        text: Child Health
      - href: child_wellness.qmd
        text: Child Wellness
      - href: travel.qmd
        text: Travel
      - href: bibliography.qmd
        text: Bibliography



      


format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 2


editor: visual

